import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { api, type TemplateType, type VisualStyle } from '../api'
import { Art } from '../components/Art'
import { Steps } from '../components/Layout'
import { useCreation } from '../store'

const templates: {value:TemplateType;label:string}[]=[{value:'comic',label:'连环画'},{value:'map',label:'故事地图'},{value:'album',label:'记录册'}]
const styles:{value:VisualStyle;label:string}[]=[{value:'anime',label:'二次元'},{value:'cyber',label:'演唱会 / 赛博'},{value:'realistic',label:'普通写实'}]
export function TemplatePage(){const c=useCreation();const nav=useNavigate();const[busy,setBusy]=useState(false);const[error,setError]=useState('');const start=async()=>{if(!c.fileIds.length)return setError('当前没有已上传的文件ID，请返回上传页面。');setBusy(true);try{const r=await api.startTask({file_ids:c.fileIds,template:c.template,style:c.style,description:c.description,materials:c.materials});c.update({taskId:r.task_id});nav('/editor')}catch(e){setError(e instanceof Error?e.message:'创建任务失败')}finally{setBusy(false)}};return <><Steps current={2}/><div className="page-heading"><h1>给回忆，选一种表达。</h1><p>选择故事模板、视觉风格和纪念物料。</p></div><div className="flow-grid"><section className="panel"><h2>01 选择故事模板</h2><div className="template-grid">{templates.map(t=><label className="choice template-choice" key={t.value}><input type="radio" name="template" checked={c.template===t.value} onChange={()=>c.update({template:t.value})}/><Art title={t.label} kind={t.value}/><strong>{t.label}</strong></label>)}</div><h2 className="spaced">02 选择视觉风格</h2><div className="option-row">{styles.map(s=><label className="choice option" key={s.value}><input type="radio" name="style" checked={c.style===s.value} onChange={()=>c.update({style:s.value})}/><span>{s.label}</span></label>)}</div><h2 className="spaced">03 实体物料</h2><div className="material-grid">{['badge','keychain','ticket','poster'].map((m,i)=><label className="choice material" key={m}><input type="checkbox" checked={c.materials.includes(m)} onChange={(e)=>c.update({materials:e.target.checked?[...c.materials,m]:c.materials.filter(x=>x!==m)})}/><b>{['◉','♧','▤','▧'][i]}</b><span>{['吧唧','钥匙扣','小票','海报'][i]}</span></label>)}</div>{error&&<p className="error-box" role="alert">{error}</p>}<div className="form-bottom"><button className="button primary" disabled={busy} onClick={start}>{busy?'正在创建任务…':'开始生成'}</button></div></section><aside className="preview-side"><span className="tag">实时选择预览</span><Art title={templates.find(t=>t.value===c.template)?.label} kind={c.template}/></aside></div></>}
